name: PaymentService CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'PaymentService/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./PaymentService
        file: ./PaymentService/Dockerfile
        push: true
        tags: ydmins/metapay-payment:latest
        platforms: linux/amd64,linux/arm64

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          docker pull ydmins/metapay-payment:latest
          docker stop metapay-payment || true
          docker rm metapay-payment || true
          docker run -d --name metapay-payment \
            --network host \
            -e PORT=8080 \
            -e SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}" \
            -e SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
            -e SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
            -e SPRING_CACHE_TYPE=NONE \
            -e SPRING_REDIS_CLUSTER_NODES="${{ secrets.SPRING_REDIS_CLUSTER_NODES }}" \
            -p 8080:8080 \
            ydmins/metapay-payment:latest
        '
